version: '3.7'

services:
  # PHP-FPM - Service
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network


  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass RedisPass2020!
    volumes:
      - ./docker/redis/data:/data
    ports:
      - "6379:6379"

    networks:
      - app-network


  # NGINX - Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true

    ports:
      - "8000:80"
      - "8443:443"

    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

    networks:
      - app-network


# Networks
networks:
  app-network:
    driver: bridge
